version: '3.8'

services:
  java-react:
    image: anushsingla/java-react:${IMAGE_TAG:-latest}
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Suhan@24510
